### ISSUE TITLE
error importing aceql on Linux platform due to attempted _winreg import

### ISSUE THREAD

**Issue by gjcarrette** [kawansoft/aceql-http-client-python#1]
In a Linux platform
```
python
Python 2.7.9 (default, Mar 16 2016, 16:28:42)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aceql
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gcarrette/lib/python2.7/site-packages/aceql/__init__.py", line 32, in <module>
    from aceql.proxy_util import *
  File "/home/gcarrette/lib/python2.7/site-packages/aceql/proxy_util.py", line 20, in <module>
    import winreg
  File "/opt/pkg/python2.7/latest/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/winreg/__init__.py", line 6, in <module>
    from _winreg import *
ImportError: No module named _winreg
```

This is after an error free
```pip install aceql```

So I think you just need to modify the `__init__.py` to avoid loading the proxy_util
unless `platform.system() == 'Windows'`

My temporary work-around is to 
```touch  /home/gcarrette/lib/python2.7/site-packages/_winreg.py```

because the ProxyUtil class only seems to be used in the test_all.py file.

**Comment by ndepomereu** [comment]
Thanks for the clean diagnosis and the workaround!
We will update asap the code.

**Comment by ndepomereu** [comment]
Windows specific classes have been removed.
